# Generated by Django 3.2.8 on 2022-08-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField()),
                ('last_run_at', models.DateTimeField(null=True)),
                ('repeat', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('from_email', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('html_message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
