# Generated by Django 3.2.4 on 2021-06-24 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FileManager', '0003_auto_20210610_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources', models.CharField(choices=[('32-1', '32 GB RAM, 1 CPU core'), ('4-1', '4 GB RAM, 1 CPU core'), ('32-16', '32 GB RAM, 16 CPU core')], default='4-1', max_length=20)),
                ('feedback_email', models.CharField(max_length=50)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileManager.file')),
            ],
        ),
    ]
