# Generated by Django 3.2.4 on 2021-08-06 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dockerManager', '0002_auto_20210806_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerprocess',
            name='resources',
            field=models.CharField(choices=[('32-1', '32 GB RAM, 1 CPU core'), ('32-16', '32 GB RAM, 16 CPU cores'), ('4-1', '4 GB RAM, 1 CPU core')], default='4-1', max_length=20),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dockerManager.dockerprocess')),
            ],
        ),
    ]
