# Generated by Django 3.2.4 on 2021-08-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerManager', '0003_auto_20210806_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='file',
            new_name='report',
        ),
        migrations.AddField(
            model_name='analysis',
            name='order',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dockerprocess',
            name='resources',
            field=models.CharField(choices=[('32-16', '32 GB RAM, 16 CPU cores'), ('32-1', '32 GB RAM, 1 CPU core'), ('4-1', '4 GB RAM, 1 CPU core')], default='4-1', max_length=20),
        ),
    ]
