# Generated by Django 3.2.4 on 2021-08-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerManager', '0004_auto_20210810_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='order',
            field=models.CharField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='report',
            field=models.CharField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='dockerprocess',
            name='resources',
            field=models.CharField(choices=[('32-16', '32 GB RAM, 16 CPU cores'), ('4-1', '4 GB RAM, 1 CPU core'), ('32-1', '32 GB RAM, 1 CPU core')], default='4-1', max_length=20),
        ),
    ]
