# Generated by Django 3.2.8 on 2022-04-04 09:51
from django.db import migrations
import logging
from ddueruemweb import settings

logger = logging.getLogger(__name__)


def _create_default_license(apps, schema_editor):
    License = apps.get_model('fileupload', 'License')
    if not License.objects.filter(label=License._default_license).exists():
        License.objects.create(label=License._default_license)
        logger.info('Created default license')


class Migration(migrations.Migration):
    dependencies = []

    operations = [migrations.RunPython(_create_default_license)]
