# Generated by Django 3.2.8 on 2022-03-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'family', 'verbose_name_plural': 'families'},
        ),
        migrations.AddField(
            model_name='file',
            name='mirrored',
            field=models.BooleanField(default=False),
        ),
    ]
