# Generated by Django 3.2.8 on 2022-04-04 17:50

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def _create_default_license(apps, schema_editor):
    """
    Create License with CC BY - Mention if not already exists after migration
    """
    License = apps.get_model('core_fileupload', 'License')
    # can not use License._default_license here, so we need to hardcode it
    if not License.objects.filter(label='CC BY - Mention').exists():
        License.objects.create(label='CC BY - Mention')
        logger.info('Created default license')



class Migration(migrations.Migration):

    dependencies = [
        ('core_fileupload', '0001_initial'),
    ]

    operations = [migrations.RunPython(_create_default_license)]
