# Generated by Django 3.2.8 on 2021-11-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_fileupload', '0002_auto_20211115_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user',
            new_name='owner',
        ),
    ]
