# Generated by Django 3.2.8 on 2022-04-11 11:22
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


def create_lic(apps, schema_editor):
    License = apps.get_model('core_fileupload', 'License')
    default_label = 'CC By - Mention'
    try:
        License.objects.get(label=default_label)
    except ObjectDoesNotExist:
        License.objects.create(label=default_label)


class Migration(migrations.Migration):
    dependencies = [
        ('core_fileupload', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_lic),
    ]
