# Generated by Django 3.2.8 on 2022-07-19 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_fileupload', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
