# Generated by Django 3.2.8 on 2022-08-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_fileupload', '0004_emailsendtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSendTask',
        ),
    ]
