# Generated by Django 3.2.8 on 2022-10-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_fileupload', '0007_file_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='confirmation_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
