# Generated by Django 3.2.8 on 2022-10-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_fileupload', '0005_delete_emailsendtask'),
        ('core_fileupload', '0008_file_confirmation_token'),
    ]

    operations = [
    ]
