# Generated by Django 3.2.8 on 2022-11-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_fileupload', '0009_merge_20221027_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_only', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('query', models.TextField()),
                ('depends_on', models.ManyToManyField(to='core_fileupload.Analysis')),
            ],
        ),
    ]
