# Generated by Django 3.2.8 on 2022-11-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_fileupload', '0010_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=False)),
                ('result', models.JSONField(null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_fileupload.analysis')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_fileupload.file')),
            ],
        ),
    ]
