# Generated by Django 4.2.2 on 2023-10-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_fileupload', '0011_analysisresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='label',
            field=models.TextField(default='CC BY - SA 4.0 DEED'),
        ),
    ]
