# Generated by Django 4.2.2 on 2023-10-23 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_fileupload', '0012_alter_license_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_fileupload.family'),
        ),
        migrations.AlterField(
            model_name='file',
            name='version',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
