# Generated by Django 4.2.2 on 2023-10-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_fileupload', '0012_file_core_fileup_owner_i_4178bf_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['owner'], name='core_fileup_owner_i_4e6325_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner'], name='core_fileup_owner_i_3c733f_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['family'], name='core_fileup_family__57b383_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['version'], name='core_fileup_version_b47e16_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['is_confirmed'], name='core_fileup_is_conf_ba01cb_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['label'], name='core_fileup_label_70ea9c_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['label'], name='core_fileup_label_fa57bd_idx'),
        ),
    ]
