# Generated by Django 4.2.2 on 2023-10-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_fileupload', '0013_family_core_fileup_owner_i_4e6325_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='core_fileup_owner_i_4178bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='core_fileup_confirm_22c787_idx',
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='core_fileup_owner_i_3c733f_idx',
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='core_fileup_version_b47e16_idx',
        ),
    ]
