# Generated by Django 4.2.2 on 2023-10-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_fileupload', '0014_remove_file_core_fileup_owner_i_4178bf_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='core_fileup_family__df0347_idx',
        ),
        migrations.RemoveIndex(
            model_name='license',
            name='core_fileup_label_70ea9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='core_fileup_label_fa57bd_idx',
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner'], name='core_fileup_owner_i_3c733f_idx'),
        ),
    ]
