# Generated by Django 4.2.2 on 2023-11-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_fileupload', '0014_file_private'),
        ('core_fileupload', '0015_remove_file_core_fileup_family__df0347_idx_and_more'),
    ]

    operations = [
    ]
