# Generated by Django 3.2.8 on 2022-04-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True)),
                ('order', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'analysis',
                'verbose_name_plural': 'analyses',
            },
        ),
        migrations.CreateModel(
            name='DockerProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources', models.CharField(choices=[('32-1', '32 GB RAM, 1 CPU core'), ('32-16', '32 GB RAM, 16 CPU cores'), ('4-1', '4 GB RAM, 1 CPU core')], default='4-1', max_length=20)),
                ('library', models.CharField(choices=[('buddy', 'BuDDy'), ('cudd', 'CUDD')], max_length=25)),
                ('working', models.BooleanField(default=False)),
                ('working_directory', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'dockerProcess',
                'verbose_name_plural': 'dockerProcesses',
            },
        ),
    ]
