# Generated by Django 3.2.8 on 2022-06-20 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_fileupload', '0001_initial'),
        ('core_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerprocess',
            name='file_to_analyse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_fileupload.file'),
        ),
    ]
