# Generated by Django 3.2.8 on 2022-08-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0009_alter_dockerprocess_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerprocess',
            name='resources',
            field=models.CharField(choices=[('4-1', '4 GB RAM, 1 CPU core'), ('32-1', '32 GB RAM, 1 CPU core'), ('32-16', '32 GB RAM, 16 CPU cores')], default='4-1', max_length=20),
        ),
    ]
