# Generated by Django 4.2.2 on 2023-10-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0018_alter_dockerprocess_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockerprocess',
            name='file_to_analyse',
        ),
        migrations.RemoveField(
            model_name='dockerprocess',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
        migrations.DeleteModel(
            name='DockerProcess',
        ),
    ]
