# Generated by Django 4.2.7 on 2024-01-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_fileupload', '0015_alter_file_tags'),
        ('core_analysis', '0019_remove_dockerprocess_file_to_analyse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_fileupload.file')),
            ],
            options={
                'unique_together': {('file', 'key')},
            },
        ),
    ]
