# Generated by Django 3.2.3 on 2021-06-03 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('format', models.CharField(choices=[('Dimacs', 'DIMACS')], default='Dimacs', max_length=6)),
                ('author', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=200)),
                ('license', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='')),
                ('tags', models.ManyToManyField(to='FileManager.Tag')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
