# Generated by Django 3.2.4 on 2021-07-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileManager', '0003_auto_20210610_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
