# Generated by Django 3.2.4 on 2021-07-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileManager', '0004_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('persistent', models.BooleanField()),
                ('last_request', models.TimeField()),
                ('requests_remaining', models.IntegerField()),
            ],
        ),
    ]
