# Generated by Django 3.2.4 on 2021-07-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileManager', '0005_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.CharField(default='', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
