# Generated by Django 3.2.8 on 2021-11-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('licence', models.CharField(choices=[('CC BY', 'Mention'), ('CC BY-NC', 'Mention - Non-commercial')], max_length=255)),
            ],
        ),
    ]
