# Generated by Django 3.2.8 on 2021-11-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='licence',
            field=models.CharField(choices=[('CC BY', 'CC BY - Mention'), ('CC BY-NC', ' CC BY-NC - Mention - Non-commercial')], max_length=255),
        ),
    ]
