# Generated by Django 3.2.8 on 2021-11-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fileupload_licence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='licence',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='license',
            field=models.CharField(choices=[('CC BY - Mention', 'CC BY - Mention'), ('CC BY-NC - Mention - Non-commercial', 'CC BY-NC - Mention - Non-commercial')], default='CC BY - Mention', max_length=255),
        ),
    ]
